### ISSUE TITLE
[FEATURE][Hide in Queue] remove from queue hiearchy tag

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-official-plugins#10]
if this tag is added don't show it in queue at all, skip this hiearchy (like display:none)

**Comment by bjsi** [comment]
I see you are a dev :) do you want to attempt to implement yourself and make a PR? Rough steps:

- register a new powerup called remove from queue hiearchy
- register some custom CSS to set `display: none;` on queue rem which have the tag.

It should be very similar to the existing code.

**Comment by bjsi** [comment]
Done
