### ISSUE TITLE
Can't close the tab

### ISSUE THREAD

**Issue by FriesenAndreas** [remnoteio/remnote-official-plugins#15]
Hi, I'm using Remnote with the Plugin "Tabs" it's a nice feature, but I can't close any tab. 
If I press the "x" nothing happened.

Please check!

Regards
Andreas

**Comment by GitMurf** [comment]
Yep I am having the same issue. Note that you can go to the workspace power up (see it in the References at bottom of any Rem page) and can delete the Rem for the tab and it will then "close" the Tab :) This is a workaround for now that I have found.

**Comment by bjsi** [comment]
Hmmm I tried to repro the other day and couldn't, I'll try again now

**Comment by bjsi** [comment]
Found the issue - only happens in native mode - as a workaround you can use the plugin in sandboxed mode until the fix is released

**Comment by GitMurf** [comment]
I was actually curious about this... for this plugin what is the difference between native and sandboxed?

**Comment by GitMurf** [comment]
Also I can confirm that with native mode turned off it does indeed work :)

**Comment by bjsi** [comment]
> I was actually curious about this... for this plugin what is the difference between native and sandboxed?

When a plugin is sandboxed it runs inside an iframe, when it is native, we basically just eval() the plugin code so it runs in the main thread. Sandboxed == higher security, native == higher performance. As this is a plugin built by the team, we made it native by default.
