### ISSUE TITLE
[FEATURE] no hierarchy tag

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-official-plugins#16]
no hierarchy tag and portal-like feature of seeing only the parent rem above

**Comment by Eikosa** [comment]
yes, what I'm talking about is the practical version of it, if there are too many titles, just entering this command will get rid of all of them practically, ideal for language exercises etc.

**Comment by bjsi** [comment]
I understand, so in the example above, you would tag the "test -> b" Rem, and all of the Rem above would be hidden?

**Comment by Eikosa** [comment]
if any rem in the hierarchy is tagged with "no hierarch" then only the test -> b will be shown

**Comment by Eikosa** [comment]
> I understand, so in the example above, you would tag the "test -> b" Rem, and all of the Rem above would be hidden?

now i think and what you said makes sense, that could be an option too

**Comment by bjsi** [comment]
![image](https://user-images.githubusercontent.com/58147075/211003833-3e14e400-cd0a-4a14-a749-65ec2d35d659.png)

This is done :)
