### ISSUE TITLE
[BUG] Mermaid Gantt breaks when using "tickInterval" parameter, & Please Enable Mermaid on Mobile

### ISSUE THREAD

**Issue by VanitasVanitatum** [remnoteio/remnote-official-plugins#22]
**Plugin Name**
Mermaid

**Describe the bug**
If you include the "tickInterval" parameter ([added](https://github.com/mermaid-js/mermaid/issues/1598) last month, [documentation](https://mermaid.js.org/syntax/gantt.html#axis-ticks)) then RemNote's Mermaid render breaks.

**To Reproduce**
Create a ##Mermaid \codeblock and paste in the following code. When you remove "%%" to uncomment "tickInterval" it stops working.

```
gantt
dateFormat  YYYY.MM.DD.HH.mm
axisFormat %Hh%Mm
%% tickInterval 30minute

title   2023.01.03 Tue
section 2023.01.03 Tue
Wake Up         : done   , B      , 2023.01.03.09.00 , 20m
Break           : crit   , Break  , after B          , 50m
Lunch & Walk    : done   , E2     , 2023.01.03.12.00 , 30m
Sleep           : done   , S      , 2023.01.03.22.30 , 30m
```

Click [here](https://mermaid-js.github.io/mermaid-live-editor/edit#pako:eNptkUFrwzAMhf-KMGSnYNyEHZZjaUcHyykbZeCLSNTWJFaKq4yN0v8-Z2lHt04n854_PSEdVd03pAq1RRax3KDQYx88CsBbLF2WerHQq5X23jJ-uMPZTVa7pIxSkoC4un1iofCOHeTGOx6ELFsWJx0BQGayXJuZNjm8DNE5UC2u5xt9jS3B6x4uVUDT89gghfmkpFeMNg_amG8pzjEPhC3AFVsHJxM7WSngJg55aTW1ux_Z54HrHdzBGrv2T-4yu82dZVNuPrJVR7T_lfvDVv_MnGU6P7MqVZ7iLl0T13-0DGCV7MiTVUV8Nhhaqyyf4j8cpK8-uVaFhIFSNezHOy0cbgN6VWywO9DpC824fG4) for a working example.

I use this for a daily schedule. Please enable on mobile (or at least make that choice toggle-able), so that we don't have to use mobile-browser desktop-mode as a clunky work-around.

**Comment by bjsi** [comment]
I just updated the mermaid plugin.
- It now uses mermaid 9.3.0 which should support tickInterval
- It is now enabled on mobile
Let me know if there are any other issues!
