### ISSUE TITLE
No Hierachy Tag not working

### ISSUE THREAD

**Issue by MarceauDauboin** [remnoteio/remnote-official-plugins#26]
![image](https://user-images.githubusercontent.com/15967899/213253425-bec43335-f156-47b5-8bc3-7060859642c5.png)

Attempting to tag a rem as "No Hierachy" doesn't work. The Powerup does not show up. Using the free version of RemNote

**Comment by bjsi** [comment]
@MarceauDauboin you can just create a Rem called No Hierarchy and use that :)

**Comment by MarceauDauboin** [comment]
Apologies for the late reply but the rems still show up with their ancestors when I practice them as flashcards. Apologies if I am using the feature incorrectly.

Tagged with No Hierachy:
![InkedScreenshot 2023-01-23 110607](https://user-images.githubusercontent.com/15967899/214002184-f245b175-5868-42a9-9237-ff148c9c1700.jpg)

Ancestors still show up when cards are practiced:
![InkedScreenshot 2023-01-23 110631](https://user-images.githubusercontent.com/15967899/214002198-6100296f-3e1b-4807-a595-b279f9e26c71.jpg)

**Comment by bjsi** [comment]
Thanks for the detailed report. I'll try to fix this week and get back to you :+1:

**Comment by MarceauDauboin** [comment]
Hi there, any updates on this by any chance?

**Comment by bjsi** [comment]
Sorry I have been so busy, I just took a look now. I think the issue may be that you misspelled the tag - it should be `No Hierarchy`. Your picture shows `No Hierachy`
