### ISSUE TITLE
Incorrect URL to tutorial in all README.md

### ISSUE THREAD

**Issue by ArthurusDent** [remnoteio/remnote-official-plugins#3]
It looks like all of the README.md files that reside in the root folder of this repo and any plugin specific subfolders have an incorrect URL for "dictionary plugin project tutorial": Page not found.

**Comment by bjsi** [comment]
Thanks @ArthurusDent I just updated them now :+1:

**Comment by ArthurusDent** [comment]
Cool! 

But you missed one: https://github.com/remnoteio/remnote-official-plugins/blob/main/README.md

**Comment by bjsi** [comment]
Fixed. Thanks again :+1:
