### ISSUE TITLE
[BUG] Hide in Queue does not hide a rem

### ISSUE THREAD

**Issue by AziEI** [remnoteio/remnote-official-plugins#33]
**Plugin Name**
Hide in Queue

**Describe the bug**
Video of the bug reproduced
https://github.com/remnoteio/remnote-official-plugins/assets/8708643/9d9e9b56-5f67-4430-9784-9636251cd5a5

**To Reproduce**
1. Create the cards as shown in the video
2. Practice a card created

**Comment by bjsi** [comment]
Merged your partial fix, I'll add a span around the  " ↔ " symbol with a class to make things easier. Should be fixed for you once the next update comes out!
