### ISSUE TITLE
Tabs plugin showing tabs vertically and using up a LOT of space.

### ISSUE THREAD

**Issue by jcpfrancesconi** [remnoteio/remnote-official-plugins#56]
Since the update to the official "Tabs" plugin yesterday, the top bar is showing the tabs vertically, taking up much more space.

![image](https://github.com/remnoteio/remnote-official-plugins/assets/49200282/2b6c0d6c-e730-4e1d-9b0c-17dfd9d1789d)

**Comment by bjsi** [comment]
Just uploaded a fix, let me know if it works

**Comment by jcpfrancesconi** [comment]
Thanks, now it's working normally.
