### ISSUE TITLE
Possibility to use use Apple voices on MacOs (spoken content) [FEATURE]

### ISSUE THREAD

**Issue by ulises-castro** [remnoteio/remnote-official-plugins#57]
**Which plugin are you requesting the feature for?** Text to speech

**Is your feature request related to a problem? Please describe.**
The current voice options are not good, I found Siri voice from Apple voices quite good,`

**Describe the solution you'd like**
Be able to use the Apple voices, basically you can activate them by using "Spoken content".  But Despite that I was able to play selected text using hammerspoon.
I guess we can run a Applescript to achieve this.

**Comment by coldenate** [comment]
Unfortunately, Apple doesn't expose the Siri voice on their APIs. Even if we interacted with it somehow with Applescript, we wouldn't be able to access that specific model :(

**Comment by coldenate** [comment]
However it wouldn't hurt for us to explore implementing OpenAI voices or Elevenlabs. Those are very human sounding (better than siri imo)
