### ISSUE TITLE
PR and Issue templates

### ISSUE THREAD

**Issue by AlexisLeon** [remnoteio/remnote-official-plugins#6]
It would be nice to have users to fill a template for new Issues and PRs so that the team can gather as many details as possible to efficiently debug an issue

[Docs for PRs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

[Docs for issues](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository)

**Comment by bjsi** [comment]
Thanks @AlexisLeon added now :)
