### ISSUE TITLE
After the update to the AI Chat feature in RemNote, a bug has appeared with the display and scrolling of the Sidebar.

### ISSUE THREAD

**Issue by PANPANJOE** [remnoteio/remnote-official-plugins#62]
After the update to the AI Chat feature in RemNote, a bug has appeared with the display and scrolling of the Sidebar.

https://github.com/user-attachments/assets/981cffce-71e0-4299-867a-e1c558416e7d

**Comment by coldenate** [comment]
Thanks! I'll add this to my list. We'll close this when done

**Comment by PANPANJOE** [comment]
Hi Nate,

Thank you so much for your response.

Looking forward to the update!

Best regards,
PAN

Nate Solis ***@***.***> 於 2024年12月6日 週五 下午3:26寫道：
