### ISSUE TITLE
[BUG] Dictionary - Not Working

### ISSUE THREAD

**Issue by hugomarins** [remnoteio/remnote-official-plugins#63]
**Plugin Name**
Dictionary

**Describe the bug**
The tab Dictionary is shown, but when selected, nothing is shown in it.

![image](https://github.com/user-attachments/assets/4e8de699-f54d-47cb-be0a-2506374fd5fc)

**Comment by hugomarins** [comment]
This orange circle and message are shown in setting - Plugins:

![image](https://github.com/user-attachments/assets/850116b2-31fb-4003-8ab3-cfccf4e3381a)

**Comment by coldenate** [comment]
Thanks. Will take a look

**Comment by hugomarins** [comment]
It worked now. I had an issue with automatic updates. I re-installed and it is working. Thanks!
