### ISSUE TITLE
[Hide in Queue] Also hides the front of the card when that card is practiced

### ISSUE THREAD

**Issue by WildGenius** [remnoteio/remnote-official-plugins#7]
See images. This is the structure for testing.
![image](https://user-images.githubusercontent.com/8071762/189529908-68d188ee-8419-4a31-ad98-ea6989dbb580.png)
The backwards card works correctly with a minor cosmetic issue.
![image](https://user-images.githubusercontent.com/8071762/189529959-687f7e5a-2e83-4aaa-94cb-e9c70b923e92.png)
The front card sadly doesn't.
![image](https://user-images.githubusercontent.com/8071762/189529987-9d9bdcf1-efdf-499f-9a0b-bd5273ad708e.png)
Hopefully the powerup can be properly limited to only affect breadcrumbs, i.e., parent rem that aren't themselves being practiced.

**Comment by bjsi** [comment]
Thanks for the report. The fix is done. But it requires a main RemNote update, so we need to wait for that to go through. I will ping this thread after it gets released :+1:.

**Comment by bjsi** [comment]
This should be fixed now. Note that you may need to manually install and reinstall the plugin, since there is a bug with plugin auto-updating.
